version: 0.2

phases:
 install:
   runtime-versions:
     java: openjdk8
   commands:
   - apt-get update -y
   - apt-get install -y 
   - apt-get install -y maven
 pre_build:
  commands:
  - echo Entered the pre_build phase...
  - java -version
  - maven --version
 build:
   commands:
   - echo Entered the build phase...
   - mvn install
 post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`


     
